// Generated by `npm run photos`. Do not edit.
//
// Intrinsic dimensions and a blur placeholder for each photograph, so a
// component can render one without importing the file and making webpack
// emit a second copy of it that nothing ever fetches.
export type PhotoMeta = { width: number; height: number; blurDataURL: string };
export const PHOTO_META: Record<string, PhotoMeta> = {
  "balcony": {
    "width": 1448,
    "height": 1086,
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoIAAYAA4BaJbACdAD5e+iJAAD+1z2sq7ngbS0nRFApn8W7asgWuUX3xh074m6gxmMVcAAA"
  },
  "beach": {
    "width": 1536,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoIAAUAA4BaJQBOjXAAUPSV4gAA/peYu2lg3OcJ37wr69kdgwBMtogHmuPrngeZEAA="
  },
  "bedroom": {
    "width": 1536,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoIAAUAA4BaJZgCdADze7UQAPzLIV9VfMlNN0qCB54M3SyfDSmFsF5yX5K2UCfbgAA="
  },
  "day-trips": {
    "width": 1492,
    "height": 1054,
    "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoIAAYAA4BaJZgCdAEO+NQjQAD80O3nm1L3lEbLvozwQzdXLM4V7KE7dKNAAA=="
  },
  "eating-in-durres": {
    "width": 1492,
    "height": 1054,
    "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoIAAYAA4BaJaACdAEfbdj+KAAA986VDAcyMkALCK2IhGEqMTrjc3XrWVtSiXdgAAA="
  },
  "hero-window": {
    "width": 1536,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoIAAUAA4BaJZQCdAEfbDOAAADeX/HIw/8y/q2nEJ/ap0DgLIAgnOAC6WAAAA=="
  },
  "host": {
    "width": 400,
    "height": 400,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoIAAgAA4BaJbACdAEf/NmvdcAA/vXRE+6CPjzOyljYfeswLS13Fw/2xErQkMv9/n9jMz3wRmaZD/YLt9imZYtq+ajAAA=="
  },
  "kitchen": {
    "width": 1536,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoIAAUAA4BaJZwAAxZYYLLAAP5V8OjvfXAUbjCkEXDDJJdtTIC1zYeQAAA="
  },
  "living-room": {
    "width": 1536,
    "height": 1024,
    "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoIAAUAA4BaJZACdAD0Ma2oAP6VCMx8PXRbuK0P3mHl00SMK8HC2xWEl16K227AAAA="
  },
  "roman-amphitheatre": {
    "width": 1492,
    "height": 1054,
    "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoIAAYAA4BaJagCdAEegF+YAPxmAJoFfyJRjN9My4ivTx5QirPevWlujWUmykFPriAAAA=="
  },
  "the-beach-hour-by-hour": {
    "width": 1492,
    "height": 1054,
    "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoIAAYAA4BaJYwCdAEPEJdnvoAA4BgVsElcR8SpPAPP1L4YLUxTfGGUN2rAAA=="
  }
};
