// Generated by `npm run photos`. Do not edit.
//
// Maps each photograph to the widths that exist in public/photos/, so the
// image loader can only ever point at a file that is really there.
export const PHOTO_WIDTHS: Record<string, number[]> = {
  "balcony": [
    256,
    480,
    768,
    1200,
    1448
  ],
  "beach": [
    256,
    480,
    768,
    1200,
    1536
  ],
  "bedroom": [
    256,
    480,
    768,
    1200,
    1536
  ],
  "hero-window": [
    256,
    480,
    768,
    1200,
    1536
  ],
  "host": [
    256,
    400
  ],
  "kitchen": [
    256,
    480,
    768,
    1200,
    1536
  ],
  "living-room": [
    256,
    480,
    768,
    1200,
    1536
  ]
};
